### ISSUE TITLE
Upgrade of package results in ERROR: The given path's format is not supported.

### ISSUE THREAD

**Issue by FibreFoX** [joachimschmidt557/chocolatey-packages-manual-automatic#15]
Upgrade of package results in ERROR: The given path's format is not supported. This already got reported on the chocolatey-project, but seems to not get any attention: https://github.com/chocolatey/choco/issues/2328

Maybe someone at this project can confirm or find the problem.

### What You Are Seeing?

Upgrade of package `godot-mono` results in error regarding unsupported format for shim creation/replacement. Maybe related to https://github.com/chocolatey/choco/issues/1517 ... not sure

Install works normal when uninstalling the old version first and installing the new version. Issue still present.

### What is Expected?

Upgrade working without problems

### How Did You Get This To Happen? (Steps to Reproduce)

1) choco install godot-mono --version 3.3.2
2) choco outdated
3) choco upgrade godot-mono

### Output Log

<details>
<summary>Full Logfile Output (chocolatey.log for step 1)</summary>

<p>
Please see this gist https://gist.github.com/FibreFoX/ab054a83cd169daf015d5d630736c652#file-1_chocolatey-log
</p>

</details>

<details>
<summary>Full Logfile Output (chocolatey.log for step 2)</summary>

<p>
Please see this gist https://gist.github.com/FibreFoX/ab054a83cd169daf015d5d630736c652#file-2_chocolatey-log
</p>

</details>

<details>
<summary>Full Logfile Output (chocolatey.log for step 3)</summary>

<p>
Please see this gist https://gist.github.com/FibreFoX/ab054a83cd169daf015d5d630736c652#file-3_chocolatey-log
</p>

</details>

**Comment by joachimschmidt557** [comment]
I think I found the issue: https://gist.github.com/FibreFoX/ab054a83cd169daf015d5d630736c652#file-3_chocolatey-log-L2210

Which is trigerred by this line in the install script:

https://github.com/joachimschmidt557/chocolatey-packages-manual-automatic/blob/dda7177ef97c6106d5faa62f309e2a10e618d91d/automatic/godot-mono/tools/chocolateyInstall.ps1#L20

The `Get-Item` returns both paths: the executable of the old version as well as the executable of the new version. I'll see if I can fix this in the next days. Thanks for the issue report!

**Comment by FibreFoX** [comment]
So you can confirm this being a problem of this package and NOT something wrong from chocolatey itself, right?

**Comment by joachimschmidt557** [comment]
@FibreFoX yes, this was a problem with my install script and not something wrong in chocolatey itself.

**Comment by FibreFoX** [comment]
This seems now to be fixed, just started the upgrade from `3.3.4` to `3.4` and had no problems anymore ;) bugfix confirmed working
