### ISSUE TITLE
Update fd to 8.3.0

### ISSUE THREAD

**Issue by mattcargile** [joachimschmidt557/chocolatey-packages-manual-automatic#16]
Can you please update the [package ](https://community.chocolatey.org/packages/fd)to the newest version?

**Comment by joachimschmidt557** [comment]
Thanks for informing me! It seems that the latest release doesn't have a `i686-pc-windows-gnu` binary, only `i686-pc-windows-msvc`. I'll switch to the `msvc` version for now.

**Comment by joachimschmidt557** [comment]
Updated to 8.3.0 in https://github.com/joachimschmidt557/chocolatey-packages-manual-automatic/commit/ff39ca3bf2bac6742e6f3a6efe4eb29e17f50b29
