### ISSUE TITLE
yt-dlg 1.8.2 -> 1.8.3 upgrade failed

### ISSUE THREAD

**Issue by opusforlife2** [joachimschmidt557/chocolatey-packages-manual-automatic#18]
Hey, I installed the package yesterday. Thanks once again for accepting it!

I tried updating it to 1.8.3 today, but something has gone wrong. The package seemed to install successfully, but I still got an Error dialogue. Strangely, the dialogue was empty.

And yt-dlg's About says it's still on 1.8.2. Any ideas what went wrong? Normally, a package install/upgrade that errors out leaves the package status unchanged. But here the choco package says it's on 1.8.3, and the software itself reports version 1.8.2.

**Comment by joachimschmidt557** [comment]
Hi! Can you try downloading the `yt-dlg.exe` binary from the [release page of yt-dlg](https://github.com/oleksis/youtube-dl-gui/releases/tag/v1.8.3) manually and check if that program has the same issue?

**Comment by opusforlife2** [comment]
I tried it. It correctly shows 1.8.3 as the version.

**Comment by opusforlife2** [comment]
Any luck finding the issue?

**Comment by joachimschmidt557** [comment]
I reproduced the issue: The executable in the chocolatey package version 1.8.3 is named `yt-dlg_x32.exe`, not `yt-dlg.exe` as in version 1.8.2.

**Comment by joachimschmidt557** [comment]
I'll modify the update script so that the `_x32` suffix will not be included in future.

**Comment by opusforlife2** [comment]
Where is this? The Releases page shows "yt-dlg.exe" for both 1.8.2 and 1.8.3.

**Comment by joachimschmidt557** [comment]
https://community.chocolatey.org/packages/yt-dlg.portable/1.8.2#files

vs

https://community.chocolatey.org/packages/yt-dlg.portable#files

**Comment by opusforlife2** [comment]
Oh. Was this copied over from the original app's choco package or something? The new one has been 64 bit for several versions, at least.

**Comment by joachimschmidt557** [comment]
The suffix `_x32` is attached by `update.ps1`. 4252df01ce793dd9d1ee73fc5acc2c049b8f0dbf changes that, so now the executable will just be called `yt-dlg.exe`.

The executable supports 64-bit Windows only, but that is not relevant for the update script as it just downloads the portable executable and packages it. Normally, when there are two separate 32-bit and 64-bit versions, the update script will attach the suffixes to the file names so the install script can choose the correct one. But as there is only one 64-bit version and no install script, the suffix can be safely removed.

**Comment by opusforlife2** [comment]
So will you publish this as an update or wait for a new upstream release?

**Comment by joachimschmidt557** [comment]
I think I'll wait for a new upstream release, then the update script will omit the suffix from the executable for the new version. If there is no upstream release for a while or if you want an updated package sooner, feel free to ping me and I'll "force push" a patched version to chocolatey (approved packages can't be modified after approval).

**Comment by opusforlife2** [comment]
Sure. The fix it contains isn't that important.

**Comment by opusforlife2** [comment]
Whoops. Forgot to close this.
