### ISSUE TITLE
Request: detach repository fork from upstream template

### ISSUE THREAD

**Issue by brogers5** [joachimschmidt557/chocolatey-packages-manual-automatic#19]
[Many other folks in the Chocolatey community](https://github.com/chocolatey-community/chocolatey-packages-template/network/members) have forked the upstream repository from which this repository is forked.

This causes issues when trying to fork another similarly-forked repository. I recently tried to do this, and encountered the following error:
![image](https://user-images.githubusercontent.com/6869577/170589475-01af182b-80bc-4476-90eb-e0e1acdc0709.png)

GitHub's limitations around sub-forks effectively forced me to delete my fork of this repository in order to create another fork. This results in some unnecessary friction when making contributions to other packages, especially while dealing with multiple WIP items across different forks.

From what I understand, this should be a quick fix. GitHub Support's Virtual Assistant should be able to handle this:
https://support.github.com/contact?flow=detach_fork&subject=Detach%20Fork&tags=rr-forks

**Comment by joachimschmidt557** [comment]
Thanks for bringing this up and providing the steps for detaching the fork!
