### ISSUE TITLE
New version (1.17.1) min browser available

### ISSUE THREAD

**Issue by mstick99** [joachimschmidt557/chocolatey-packages-manual-automatic#8]

**Comment by gep13** [comment]
@joachimschmidt557 just wanted to follow up with this.  Are you in a position to provide an update for this package?  Thanks

**Comment by joachimschmidt557** [comment]
https://chocolatey.org/packages/min.portable/1.17.3 is out now. It seemed like 1.17.1 only included x86_64 binaries and no x86 binaries and the update script didn't trigger. Can this issue be closed as resolved? @gep13  @mstick99

**Comment by gep13** [comment]
Sounds good to me! Thanks for following up with this!
