### ISSUE TITLE
Shotcut auto update fails since v20.10.31 because of discontinued 32-bit builds

### ISSUE THREAD

**Issue by arthurrump** [joachimschmidt557/chocolatey-packages-manual-automatic#9]
There have been several new releases of Shotcut since the version (v20.09.27) currently available on Chocolatey. The problem seems to be that they no longer publish 32-bit builds, so now the automatic update script fails when trying to find the url for it.

**Comment by joachimschmidt557** [comment]
I will look into this.

**Comment by joachimschmidt557** [comment]
The chocolatey versions are on the latest version again.
